#!/Users/ton/Desktop/projects/mitmproxy/.venv/bin/python3
# -*- coding: utf-8 -*-
import sys
from mitmproxy.tools.main import mitmdump
if __name__ == "__main__":
    if sys.argv[0].endswith("-script.pyw"):
        sys.argv[0] = sys.argv[0][:-11]
    elif sys.argv[0].endswith(".exe"):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(mitmdump())
